trigger:
- master
- feature/*

pool:
  vmImage: windows-latest

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
  - job: build
    steps:    
      - script: sqlpackage.exe /version
        workingDirectory: C:\Program Files\Microsoft SQL Server\150\DAC\bin\
        displayName: 'get sqlpackage version'
      
      - task: VSBuild@1
        inputs:
          solution: '**\sql\**\*.sln'
          msbuildArgs: '/p:OutDir=$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()
  
  - deployment: 
    displayName: Azure Web App Deployment
    environment: develop
    dependsOn: build
    strategy:
      runOnce:
        deploy:
          steps:    
            - task: SqlAzureDacpacDeployment@1
              inputs:
                azureSubscription: 'AzureServiceConnection'
                AuthenticationType: 'server'
                ServerName: 'sql-udp.database.windows.net'
                DatabaseName: 'sqludp'
                SqlUsername: 'wesley'
                SqlPassword: '$(sqlPassword)'
                deployType: 'DacpacTask'
                DeploymentAction: 'Publish'
                DacpacFile: '$(build.artifactstagingdirectory)/sql-template.dacpac'
                IpDetectionMethod: 'AutoDetect'